title: Jung Park
theme: jekyll-theme-minimal
#theme: jekyll-theme-slate
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am an analyst with over 4 years of experience in providing solutions using data, reports and procedural inefficiencies. Dedicated to improving system procedures through implementing automation tools that maximize quality and minimize errors. Observant and detail-oriented in monitoring and improving production activities. 
  <br><br>
  <a href="https://www.linkedin.com/in/jung-min-park-10133621b/"> <img src="https://img.shields.io/badge/LinkedIn-blue?logo=LinkedIn"> </a> 
  <br><br>
#<a href="https://rpubs.com/jacoblundeen"> <img src="https://img.shields.io/badge/RPubs-blue?logo=R"> </a>