title: Jung Park
theme: jekyll-theme-minimal
#theme: jekyll-theme-slate
description: > # your text below (remove <br> elements if you don't need line breaks)
  Mortgage operations and risk specialist with 18+ years of experience spanning underwriting, post-funding, and quality control. Proven track record of combining mortgage domain expertise with technical tools—including SQL, Python, JavaScript (BytePro macros), and spreadsheet automation—to validate loan-level data, optimize operational workflows, and generate targeted audit reporting.
  <br><br>
  <a href="https://www.linkedin.com/in/jung-min-park-10133621b/"> <img src="https://img.shields.io/badge/LinkedIn-blue?logo=LinkedIn"> </a> 
  <br><br>
#<a href="https://rpubs.com/jacoblundeen"> <img src="https://img.shields.io/badge/RPubs-blue?logo=R"> </a>
